### ISSUE TITLE
Error starting fritzbox plugin

### ISSUE THREAD

**Issue by joystick666** [tommasomarchionni/homebridge-FRITZBox#1]
Hi I configured the config.json file to my needs, but when I start homebridge I get the following error:

There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token {
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by tommasomarchionni** [comment]
The problem is in your config.json. Which editor did you use? Try another editor..now this plugin is work in progress. I will release a working version with the possibility to enable or disable WIFI Guest in the next week!
