### ISSUE TITLE
Error: Cannot find module './FritzBoxApi.js'

### ISSUE THREAD

**Issue by kohlsalem** [tommasomarchionni/homebridge-FRITZBox#4]
Hi, 

trying to install the plugin via "sudo npm install  -g homebridge-fritzbox" on a freshly installed and freshly updated pi with running node-v4.2.4-linux-armv7l and homebridge.

when i start the bridge, i get a 
# 

ERROR LOADING PLUGIN homebridge-fritzbox:
Error: Cannot find module './FritzBoxApi.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-fritzbox/libs/ItemFactory.js:5:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
#     at require (module.js:385:17)

Best
Michael

**Comment by tommasomarchionni** [comment]
Can you try with last version (0.1.22)? Now it should be fixed.

**Comment by kohlsalem** [comment]
Superfast, thanks, it registers now!

I can not proof it actually working, since i have other issues with my installation...
