### ISSUE TITLE
Error after startup

### ISSUE THREAD

**Issue by kohlsalem** [tommasomarchionni/homebridge-FRITZBox#5]
After providing correct Ip/credentials, i run now into a new issue; can you have a look:

Best
Michael

/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54
        self.log('WifiGuestItem - Invalid response.');
        ^

ReferenceError: self is not defined
    at WifiGuestItem.checkItemState (/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54:9)
    at WifiGuestItem.updateCharacteristics (/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:45:24)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fritzbox/libs/Subscriber.js:22:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by SmoothMC** [comment]
same issue here with a 7490 FritzOS 6.50

/usr/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54
        self.log('WifiGuestItem - Invalid response.');
        ^
ReferenceError: self is not defined
    at WifiGuestItem.checkItemState (/usr/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54:9)
    at WifiGuestItem.updateCharacteristics (/usr/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:45:24)
    at Request._callback (/usr/lib/node_modules/homebridge-fritzbox/libs/Subscriber.js:22:22)
    at Request.self.callback (/usr/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

**Comment by Pixxelfragger** [comment]
Hey i've got the same issue. I'm using the FritzBox 7490 with FritzOS 6.50

## The errormessage shows: 

/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54
        self.log('WifiGuestItem - Invalid response.');
        ^

ReferenceError: self is not defined
    at WifiGuestItem.checkItemState (/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:54:9)
    at WifiGuestItem.updateCharacteristics (/usr/local/lib/node_modules/homebridge-fritzbox/items/WifiGuestItem.js:45:24)
    at Request._callback (/usr/local/lib/node_modules/homebridge-fritzbox/libs/Subscriber.js:22:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fritzbox/node_modules/request/request.js:963:12)

Can you perhaps look for this error?
Thanks...

**Comment by fiorrr** [comment]
Same issue here.

Does it have to do anything with the firmware version? Are you all on >6.50?

**Comment by MarvAmBass** [comment]
Same issue here
